[package]
name = "mpalsts"
edition.workspace = true
version.workspace = true
license.workspace = true
description.workspace = true

[workspace]
resolver = "3"
members = ["crates/als", "crates/cli", "crates/gui", "crates/shared", "crates/sync", "crates/theme-switch"]

[workspace.package]
version = "1.0.1"
edition = "2024"
license = "MIT"
description = "Multiplatform theme switcher using the ambient light sensor."

[lints]
workspace = true

[workspace.lints.clippy]
needless_return = "allow"

[workspace.lints.rust]
async_fn_in_trait = "allow"
unused_imports = "deny"

[dependencies]
mpalsts_cli = { path = "./crates/cli", default-features = false }

[features]
default = ["include_gui"]
include_gui = ["mpalsts_cli/include_gui"]

[workspace.dependencies]
anyhow = "1.0.102"
auto-launch = "0.6.0"
directories = "6.0.0"
dotenv = "0.15.0"
futures = "0.3.32"
ron = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tracing = "0.1"
tracing-subscriber = "0.3.23"


# these should only be opted-into when building for macos
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-core-foundation = "0.3.2"
objc2-foundation = "0.3.2"


[package.metadata.bundle]
name = "Multi-platform ALS Theme Switcher"
identifier = "com.stboyden.mpalsts"

[package.metadata.generate-rpm]
assets = [
  { source = "target/release/mpalsts", dest = "/usr/bin/mpalsts", mode = "755" }
]

[package.metadata.deb]
assets = [
  { source = "target/release/mpalsts", dest = "/usr/bin/mpalsts", mode = "755" }
]
