name: Clippy

on:
  push:
  pull_request:

jobs:
  clippy:
    name: cargo clippy
    runs-on: docker-arm
    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache curl ca-certificates nodejs \
            musl-dev build-base git pkgconfig wayland-dev \
            fontconfig-dev cmake musl-utils
          update-ca-certificates

          echo "Processors: $(nproc)"

          echo "CC=$(which cc)" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Cargo downloads and build output
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('Cargo.lock', 'Cargo.toml', 'rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-clippy-
            ${{ runner.os }}-cargo-

      - name: Install Rust
        run: |
          if ! command -v rustup; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
          fi

      - name: Install Rust toolchain
        run: rustup show

      - name: Run Clippy
        run: cargo clippy -j $(nproc) --workspace --all-targets --all-features -- -D warnings
