[package]
name = "mpalsts_sync"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[features]
default = ["cloudkit"]
cloudkit = [
  "dep:block2",
  "dep:objc2",
  "dep:objc2-core-foundation",
  "dep:objc2-foundation",
  "dep:objc2-cloud-kit",
]

[build-dependencies]
cfg_aliases = "0.2.1"

[dependencies]
mpalsts_shared.path = "../shared"
serde.workspace = true
thiserror.workspace = true

# enabled when cloudkit feature is enabled
block2 = { workspace = true, optional = true }
objc2 = { workspace = true, optional = true }
objc2-core-foundation = { workspace = true, optional = true }
objc2-foundation = { workspace = true, optional = true }
objc2-cloud-kit = { version = "0.3.2", optional = true }

[lints]
workspace = true
