[package]
name = "mpalsts_sensors"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
async-stream = "0.3.6"
futures-time = "3.1.0"
thiserror = "2.0.18"

dotenv.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
smol = "2.0.2"

[target.'cfg(target_os = "linux")'.dependencies]
glob = "0.3.3"

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"
objc2-core-foundation = "0.3.2"
objc2-foundation = "0.3.2"
objc2-io-kit = "0.3.2"
objc2-sensor-kit = "0.3.2"
